//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EmployeesManagementAssistant.rc
//
#define IDP_OLE_INIT_FAILED             100
#define ID_WINDOW_MANAGER               127
#define IDR_MAINFRAME                   128
#define IDR_EmployeesManagementAssistantTYPE 130
#define IDR_EmployeesTYPE               131
#define IDR_LIST_VIEW_CONTEXT_MENU      132
#define IDD_EMPLOYEES_DIALOG            133
#define IDD_TASK_STATES_DIALOG          134
#define IDD_TASK_PRIORITIES_DIALOG      136
#define IDD_TASKS_DIALOG                137
#define IDR_TasksTYPE                   138
#define IDR_TaskPrioritiesTYPE          139
#define IDR_TaskStatesTYPE              140
#define IDD_LOGIN_DIALOG                141
#define IDC_GRB_EMPLOYEES_SYSTEM_DATA   1000
#define IDC_STT_EMPLOYEES_STATUS        1001
#define IDC_CMB_EMPLOYEES_STATUS        1002
#define IDC_STT_EMPLOYEES_ACCESS_LEVEL  1003
#define IDC_CMB_EMPLOYEES_ACCESS_LEVEL  1004
#define IDC_STT_EMPLOYEES_PASSWORD      1005
#define IDC_EDB_EMPLOYEES_PASSWORD      1006
#define IDC_EDB_EMPLOYEES_PERSONAL_KEY  1008
#define IDC_GRB_EMPLOYEES_MAIN_DATA     1009
#define IDC_STT_EMPLOYEES_FIRST_NAME    1010
#define IDC_EDB_EMPLOYEES_FIRST_NAME    1011
#define IDC_STT_EMPLOYEES_MIDDLE_NAME   1012
#define IDC_EDB_EMPLOYEES_MIDDLE_NAME   1013
#define IDC_STT_EMPLOYEES_LAST_NAME     1014
#define IDC_EDB_EMPLOYEES_LAST_NAME     1015
#define IDC_STT_EMPLOYEES_IDENTIFIER    1016
#define IDC_EDB_EMPLOYEES_IDENTIFIER    1017
#define IDC_STT_EMPLOYEES_SALARY        1018
#define IDC_EDB_EMPLOYEES_SALARY        1019
#define IDC_GRB_EMPLOYEES_PHONE_NUMBERS 1020
#define IDC_STT_EMPLOYEES_PERSONAL_PHONE_NUMBER 1021
#define IDC_EDB_EMPLOYEES_PERSONAL_PHONE_NUMBER 1022
#define IDC_STT_EMPLOYEES_BUSINESS_PHONE_NUMBER 1023
#define IDC_EDB_EMPLOYEES_BUSINESS_PHONE_NUMBER 1024
#define IDC_STT_EMPLOYEES_EMAIL_ADDRESS 1025
#define IDC_EDB_EMPLOYEES_EMAIL_ADDRESS 1026
#define IDC_GRB_EMPLOYEES_ADDRESSES     1027
#define IDC_STT_EMPLOYEES_HOME_ADDRESS  1028
#define IDC_EDB_EMPLOYEES_HOME_ADDRESS  1029
#define IDC_STT_EMPLOYEES_WORK_ADDRESS  1030
#define IDC_EDB_EMPLOYEES_WORK_ADDRESS  1031
#define IDC_STT_TASK_STATES_NAME        1032
#define IDC_GRB_EMPLOYEES_SYSTEM_DATA2  1032
#define IDC_GRB_EMPLOYEES_PERSONAL_KEY  1032
#define IDC_EDB_TASK_STATES_NAME        1033
#define IDC_STT_TASK_PRIORITIES_NAME    1034
#define IDC_EDB_TASK_PRIORITIES_NAME    1035
#define IDC_STT_TASKS_NAME              1036
#define IDC_EDB_TASKS_NAME              1037
#define IDC_STT_TASKS_PRIORITY          1038
#define IDC_CMB_TASKS_PRIORITY          1039
#define IDC_STT_TASKS_STATE             1040
#define IDC_CMB_TASKS_STATE             1041
#define IDC_STT_TASKS_ASSIGN_TO         1042
#define IDC_CMB_TASKS_ASSIGN_TO         1043
#define IDC_STT_ASKS_ASSIGN_FROM        1044
#define IDC_CMB_TASKS_ASSIGN_FROM       1045
#define IDC_GRB_TASKS_DESCRIPTION       1046
#define IDC_EDB_TASKS_DESCRIPTION       1047
#define IDC_EDB_LOGIN_IDENTIFIER        1048
#define IDC_EDB_LOGIN_PASSWORD          1049
#define IDC_STT_LOGIN_IDENTIFIER        1050
#define IDC_STT_LOGIN_PASSWORD          1051
#define IDC_CMB_TASK_PRIORITIES_LEVEL   1052
#define IDC_STT_TASK_PRIORITIES_LEVEL   1053
#define IDC_CHB_TASK_STATES_IS_FOR_ARCHIVE 1054
#define ID_CONTEXT_MENU_VIEW            32700
#define ID_CONTEXT_MENU_INSERT          32701
#define ID_CONTEXT_MENU_UPDATE          32702
#define ID_CONTEXT_MENU_DELETE          32703
#define ID_CONTEXT_MENU_SEARCH          32704
#define ID_CONTEXT_MENU_REFRESH         32705
#define ID_EMPLOYEES_VIEW               32706
#define ID_TASKS_VIEW                   32707
#define ID_TASK_PRIORITIES_VIEW         32708
#define ID_TASK_STATES_VIEW             32709
#define ID_EMPLOYEE_PROFILE             32710

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32711
#define _APS_NEXT_CONTROL_VALUE         1055
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
